services:
  airflow_postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - postgres_airflow:/var/lib/postgresql/data

  airflow_redis:
    image: redis:latest
    container_name: airflow_redis
    ports:
      - "6380:6379"

  airflow_webserver:
    image: apache/airflow:2.6.3
    container_name: airflow_webserver
    depends_on:
      - airflow_postgres
      - airflow_redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://airflow_redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: secretkey123
    ports:
      - "8081:8080"
    volumes:
      - ../dags:/opt/airflow/dags
    command: webserver

  airflow_scheduler:
    image: apache/airflow:2.6.3
    container_name: airflow_scheduler
    depends_on:
      - airflow_webserver
      - airflow_postgres
      - airflow_redis
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://airflow_redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow_postgres:5432/airflow
    volumes:
      - ../dags:/opt/airflow/dags
    command: scheduler

volumes:
  postgres_airflow:
